### ISSUE TITLE
Ruins old API access

### ISSUE THREAD

**Issue by natanavra** [WP-API/Basic-Auth#45]
Old API becomes unusable because of this plugin.

Error received: 
<div id="current-theme" class="has-screenshot">
    <br />
    <b>Fatal error</b>: Uncaught Error: Call to a member function get_page_permastruct() on null in /var/www/html/wp/wp-includes/link-template.php:357
    Stack trace: #0 /var/www/html/wp/wp-includes/link-template.php(320): _get_page_link(Object(WP_Post), false, false) #1
    /var/www/html/wp/wp-includes/link-template.php(144): get_page_link(Object(WP_Post), false, false) #2 /var/www/html/wp/wp-content/plugins/woocommerce/includes/wc-page-functions.php(72):
    get_permalink(Object(WP_Post)) #3 /var/www/html/wp/wp-content/plugins/woocommerce/includes/wc-account-functions.php(30):
    wc_get_page_permalink('myaccount') #4 /var/www/html/wp/wp-includes/class-wp-hook.php(300): wc_lostpassword_url('https://sweet21...')

**Comment by chrishaff** [comment]
Dumb question: What's the old API?

**Comment by natanavra** [comment]
Sorry, this thing is wayyy to old and I don't remember.
Apparently I didn't know how to write issues back then :-D
